version: 0.1.5.{build}
shallow_clone: true
build_script:
- cmd: >-
    echo [[Build started]]

    node bootstrap.js --version

    node bootstrap.js hexa.json

    move hexa-node.js hexa-bootstrap.js

    node hexa-bootstrap.js hexa.json

    move hexa-node.js hexa-self.js

    node hexa-self.js hexa.json

    dir

    echo [[Build complete]]
artifacts:
- path: hexa-node.js
  name: hexa
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
